apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-afr-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scc-afr-redis
  template:
    metadata:
      labels:
        app: scc-afr-redis
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: scc-afr-redis
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 1Gi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: scc-afr-redis
spec:
  ports:
  - port: 6379
  selector:
    app: scc-afr-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-afr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scc-afr-app
  template:
    metadata:
      labels:
        app: scc-afr-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: scc-afr-app
        image: amtorrinha/scc2021-app
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 1Gi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "scc-afr-redis"
---
apiVersion: v1
kind: Service
metadata:
  name: scc-afr-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: scc-afr-app
