# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: scc-afr
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: scc-afr-mongoDB
    
    ports:
            - 27017:27017
    volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro